
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __CLOCK_TYPEBUILTINS_H__
#define __CLOCK_TYPEBUILTINS_H__ 1

#ifdef __cplusplus
extern "C" {
#endif

/* --- ../../applets/clock/clock-utils.h --- */
#define CLOCK_TYPE_FORMAT clock_format_get_type()
GType clock_format_get_type (void);
#ifdef __cplusplus
}
#endif

#endif /* __CLOCK_TYPEBUILTINS_H__ */

/* Generated data ends here */

