/*
 * Generated by gdbus-codegen 2.58.3 from org.kde.StatusNotifierWatcher.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __SN_WATCHER_V0_GEN_H__
#define __SN_WATCHER_V0_GEN_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.kde.StatusNotifierWatcher */

#define SN_TYPE_WATCHER_V0_GEN (sn_watcher_v0_gen_get_type ())
#define SN_WATCHER_V0_GEN(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SN_TYPE_WATCHER_V0_GEN, SnWatcherV0Gen))
#define SN_IS_WATCHER_V0_GEN(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SN_TYPE_WATCHER_V0_GEN))
#define SN_WATCHER_V0_GEN_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), SN_TYPE_WATCHER_V0_GEN, SnWatcherV0GenIface))

struct _SnWatcherV0Gen;
typedef struct _SnWatcherV0Gen SnWatcherV0Gen;
typedef struct _SnWatcherV0GenIface SnWatcherV0GenIface;

struct _SnWatcherV0GenIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_register_host) (
    SnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_service);

  gboolean (*handle_register_item) (
    SnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_service);

  gboolean  (*get_is_host_registered) (SnWatcherV0Gen *object);

  gint  (*get_protocol_version) (SnWatcherV0Gen *object);

  const gchar *const * (*get_registered_items) (SnWatcherV0Gen *object);

  void (*host_registered) (
    SnWatcherV0Gen *object);

  void (*item_registered) (
    SnWatcherV0Gen *object,
    const gchar *arg_service);

  void (*item_unregistered) (
    SnWatcherV0Gen *object,
    const gchar *arg_service);

};

GType sn_watcher_v0_gen_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *sn_watcher_v0_gen_interface_info (void);
guint sn_watcher_v0_gen_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void sn_watcher_v0_gen_complete_register_item (
    SnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation);

void sn_watcher_v0_gen_complete_register_host (
    SnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void sn_watcher_v0_gen_emit_item_registered (
    SnWatcherV0Gen *object,
    const gchar *arg_service);

void sn_watcher_v0_gen_emit_item_unregistered (
    SnWatcherV0Gen *object,
    const gchar *arg_service);

void sn_watcher_v0_gen_emit_host_registered (
    SnWatcherV0Gen *object);



/* D-Bus method calls: */
void sn_watcher_v0_gen_call_register_item (
    SnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean sn_watcher_v0_gen_call_register_item_finish (
    SnWatcherV0Gen *proxy,
    GAsyncResult *res,
    GError **error);

gboolean sn_watcher_v0_gen_call_register_item_sync (
    SnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GError **error);

void sn_watcher_v0_gen_call_register_host (
    SnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean sn_watcher_v0_gen_call_register_host_finish (
    SnWatcherV0Gen *proxy,
    GAsyncResult *res,
    GError **error);

gboolean sn_watcher_v0_gen_call_register_host_sync (
    SnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *const *sn_watcher_v0_gen_get_registered_items (SnWatcherV0Gen *object);
gchar **sn_watcher_v0_gen_dup_registered_items (SnWatcherV0Gen *object);
void sn_watcher_v0_gen_set_registered_items (SnWatcherV0Gen *object, const gchar *const *value);

gboolean sn_watcher_v0_gen_get_is_host_registered (SnWatcherV0Gen *object);
void sn_watcher_v0_gen_set_is_host_registered (SnWatcherV0Gen *object, gboolean value);

gint sn_watcher_v0_gen_get_protocol_version (SnWatcherV0Gen *object);
void sn_watcher_v0_gen_set_protocol_version (SnWatcherV0Gen *object, gint value);


/* ---- */

#define SN_TYPE_WATCHER_V0_GEN_PROXY (sn_watcher_v0_gen_proxy_get_type ())
#define SN_WATCHER_V0_GEN_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SN_TYPE_WATCHER_V0_GEN_PROXY, SnWatcherV0GenProxy))
#define SN_WATCHER_V0_GEN_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SN_TYPE_WATCHER_V0_GEN_PROXY, SnWatcherV0GenProxyClass))
#define SN_WATCHER_V0_GEN_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SN_TYPE_WATCHER_V0_GEN_PROXY, SnWatcherV0GenProxyClass))
#define SN_IS_WATCHER_V0_GEN_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SN_TYPE_WATCHER_V0_GEN_PROXY))
#define SN_IS_WATCHER_V0_GEN_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SN_TYPE_WATCHER_V0_GEN_PROXY))

typedef struct _SnWatcherV0GenProxy SnWatcherV0GenProxy;
typedef struct _SnWatcherV0GenProxyClass SnWatcherV0GenProxyClass;
typedef struct _SnWatcherV0GenProxyPrivate SnWatcherV0GenProxyPrivate;

struct _SnWatcherV0GenProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  SnWatcherV0GenProxyPrivate *priv;
};

struct _SnWatcherV0GenProxyClass
{
  GDBusProxyClass parent_class;
};

GType sn_watcher_v0_gen_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SnWatcherV0GenProxy, g_object_unref)
#endif

void sn_watcher_v0_gen_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SnWatcherV0Gen *sn_watcher_v0_gen_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
SnWatcherV0Gen *sn_watcher_v0_gen_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void sn_watcher_v0_gen_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SnWatcherV0Gen *sn_watcher_v0_gen_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
SnWatcherV0Gen *sn_watcher_v0_gen_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define SN_TYPE_WATCHER_V0_GEN_SKELETON (sn_watcher_v0_gen_skeleton_get_type ())
#define SN_WATCHER_V0_GEN_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SN_TYPE_WATCHER_V0_GEN_SKELETON, SnWatcherV0GenSkeleton))
#define SN_WATCHER_V0_GEN_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SN_TYPE_WATCHER_V0_GEN_SKELETON, SnWatcherV0GenSkeletonClass))
#define SN_WATCHER_V0_GEN_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SN_TYPE_WATCHER_V0_GEN_SKELETON, SnWatcherV0GenSkeletonClass))
#define SN_IS_WATCHER_V0_GEN_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SN_TYPE_WATCHER_V0_GEN_SKELETON))
#define SN_IS_WATCHER_V0_GEN_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SN_TYPE_WATCHER_V0_GEN_SKELETON))

typedef struct _SnWatcherV0GenSkeleton SnWatcherV0GenSkeleton;
typedef struct _SnWatcherV0GenSkeletonClass SnWatcherV0GenSkeletonClass;
typedef struct _SnWatcherV0GenSkeletonPrivate SnWatcherV0GenSkeletonPrivate;

struct _SnWatcherV0GenSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  SnWatcherV0GenSkeletonPrivate *priv;
};

struct _SnWatcherV0GenSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType sn_watcher_v0_gen_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SnWatcherV0GenSkeleton, g_object_unref)
#endif

SnWatcherV0Gen *sn_watcher_v0_gen_skeleton_new (void);


G_END_DECLS

#endif /* __SN_WATCHER_V0_GEN_H__ */
